local dap_install = require("dap-install")

-- dap_install.setup({
--     installation_path = vim.api.nvim_eval('$HOME') .. "/Apps/nvim-dap/",
--     verbosely_call_debuggers = false,
-- })
--
-- dap_install.config("python", {
--     adapters = {
--         test = {
--             type = 'executable';
--             command = 'python3';
--             args = {'-m', 'debugpy.adapter'};
--         },
--         remote = {
--             type = 'server';
--             host = '127.0.0.1';
--             port = 5678;
--         }
--     },
--     configurations = {
--         {
--             type = 'test';
--             request = 'launch';
--             name = 'Local';
--             program = '${file}';
--         },
--         {
--             type = 'remote';
--             request = 'attach';
--             name = 'Remote';
--         }
--     }
-- })
